Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blogs.urls', namespace='blogs')),
    
]

blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    
    # Страница для новой темы
    path('new_post/', views.new_post, name='new_post'),
    
    # Страница редактирования темы
    path('edit_post/<blog_id>/', views.edit_post, name='edit_post'),
    
]

users/urls.py
"""Определяет схему URL для пользователей Blog"""

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    # Страница входа
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

    # Страница выхода
    path('logout/', views.logout_view, name='logout'),

    # Страница регистрации
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return '{} - {}'.format(self.title, self.text)

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import BlogPost
from .forms import BlogPostForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    blogs = BlogPost.objects.order_by('-date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/index.html', context)


@login_required
def new_post(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # Данные не отправлялись, создается пустая форма.
        form = BlogPostForm
    else:
        # Отправлены данные POST; обработать данные.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return HttpResponseRedirect(reverse('blogs:index'))
            
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, blog_id):
    """Редактирует существующую запись."""
    blog = BlogPost.objects.get(id=blog_id)
    check_topic_owner(blog.owner, request.user)
    
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = BlogPostForm(instance=blog)
    else:
        # Отправка данных POST; обработать данные.
        form = BlogPostForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:index'))
                                                    
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)


def check_topic_owner(post_owner, current_user):
    """
    Проверяет, что пользователь, связанный с темой является 
        текущим пользователем
    """
    if post_owner != current_user:
        raise Http404

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    """Завершает сеанс работы с приложением."""
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))
    
def register(request):
    """Регистрирует нового пользователя"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid:
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form':form}
    return render(request, 'users/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    
    <title>Eskander's Blog for everyone</title>
    
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  
  </head>
  
    <body>
    <!-- Статическая навигационная панель -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
      
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'blogs:index' %}">
              Eskander's Blog for everyone</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
        
      </div>
    </nav>
  
        <div class="container">
          <div class="page-header">
            {% block header %}{% endblock header %}
          </div>
          <div>
            {% block content %}{% endblock content %}
          </div>
          
        </div><!-- /container -->

    </body>
</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>
    <p>
      <a href="{% url 'blogs:edit_post' blog.id %}">{{ blog }}</a>
    </p>
  </h2>
{% endblock header %}

{% block content %}

  <p>Edit post:</p>

  <form action="{% url 'blogs:edit_post' blog.id %}" 
    class="form" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
    <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}
  
  </form>
  
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <div class='jumbotron'>
    <h2>Post everything you want.</h2>
  </div>
{% endblock header %}

{% block content %}

{% if user.is_authenticated %}
  <a href="{% url 'blogs:new_post' %}">
    <button class="btn btn-primary">Add post</button>
  </a>
<ul>
  {% for blog in blogs %}
    <li>
      <h3>
        {{ blog.title }}
          <small>
            {{ blog.date_added|date:'M d, Y H:i' }}
          </small>
      </h3>
    
        {{ blog.text|linebreaks }}
          <small>
            <a href="{% url 'blogs:edit_post' blog.id %}">edit post</a>
          </small>
    </li>
  {% empty %}
    <li>No posts have been added yet.</li>
  {% endfor %}
  {% else %}
  <h3>
  <a href="{% url 'users:register' %}">Register</a>
  or
  <a href="{% url 'users:login' %}">Login</a>
  to add or edit a post
  </h3>
  {% endif %}
</ul>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add new post:</h2>
{% endblock header %}

{% block content %}
  
  <form action="{% url 'blogs:new_post' %}" method='post'
        class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
    <button name="submit" class="btn btn-primary">add entry</button>
    {% endbuttons %}
  
  </form>
  
{% endblock content %}

users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
  </form>
  
{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2><p>Registration</p></h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">register</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
  </form>
  
{% endblock content %}